### ISSUE TITLE
First Deliverables ready for review

### ISSUE THREAD

**Issue by Carson-Ray** [qtgiebel/MOBAD#1]
@pawaitemadisoncollege Our first deliverables for the team project are ready for review

**Comment by pawaitemadisoncollege** [comment]
Hey Team! Love the team name - thanks for being understanding and flexible about that! @Carson-Ray and @qtgiebel 

- [x] Team resume is well done. It provides a good introduction and does a good job highlighting each of your strengths. One typo: "engaging manager" => "engaging manner"
- [x] Problem statement would be improved by explaining "MOBA". :)
- [x] To understand the scope of this project, can you share what resources will be returned and the attributes included? Also which operations (get, put, post, delete). For a service that focused on Vehicle data, that might include: 

- a Vehicle resource with make, model, year, vehicle id number (vin), color, safety rating, etc.
- operations might include get by vin, get by make, get by model, get by year, delete by id, etc.

- [x] Add a .gitignore sooner than later to prevent unwanted stuff from making it out to GitHub, and to prevent developer-specific environment details from messing up other dev environments.

**Comment by qtgiebel** [comment]
Thank you for pointing these out. I have made the simple fixes as you suggested. @Carson-Ray and I will discuss how we want to structure the resources and operations in our next meeting.

**Comment by Carson-Ray** [comment]
We have changed our readme to reflect the resources and related attributes, as well as the GET operations we will be serving. We updated the previously titled resources section to instead be the tech stack we will be using.

**Comment by pawaitemadisoncollege** [comment]
@Carson-Ray and @qtgiebel Thanks for the updates.

With regard to the resources your api returns, is a good name for that "dictionary-resources", or "terms", or "words" or??? Once you decide the resource name, then following restful naming best practices, the requests would be something like:

GET /your-plural-resource-name/{keyword}
GET /your-plural-resource-name
GET /your-plural-resource-name/{title}


https://restfulapi.net/resource-naming/

**Comment by pawaitemadisoncollege** [comment]
One more thing - also include which formats you'll return - for example: json, xml, plain text, jpg, html, etc.

**Comment by Carson-Ray** [comment]
Thank you for the continued input! I have pushed the changes regarding the naming conventions and have added to the readme that we will be serving our responses in json format

**Comment by pawaitemadisoncollege** [comment]
Thanks for the updates! With those resources, operations, and the AWS resources you are using, this is just the right scope. Can't wait to see it in action!
